# Generated by Django 3.2.6 on 2021-08-25 17:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equity_Security_Master',
            fields=[
                ('asset_id', models.CharField(default='needs_id', max_length=40, primary_key=True, serialize=False, verbose_name='asset id')),
                ('ticker', models.CharField(blank=True, max_length=40, null=True, verbose_name='ticker')),
                ('comnam', models.CharField(blank=True, max_length=40, null=True, verbose_name='Company Name')),
                ('conid', models.CharField(blank=True, max_length=40, null=True, verbose_name='conid')),
                ('cusip', models.CharField(blank=True, max_length=40, null=True, verbose_name='cusip')),
                ('isin', models.CharField(blank=True, max_length=40, null=True, verbose_name='isin')),
                ('valid_date', models.DateField(default=django.utils.timezone.now)),
                ('siccd', models.CharField(blank=True, max_length=40, null=True, verbose_name='industry code')),
                ('country_code', models.CharField(blank=True, max_length=40, null=True, verbose_name='country code')),
                ('prim_exch', models.CharField(blank=True, max_length=40, null=True, verbose_name='prim exch')),
                ('currency', models.CharField(blank=True, max_length=40, null=True, verbose_name='currency')),
                ('bnchmrk', models.CharField(blank=True, max_length=40, null=True, verbose_name='benchmark')),
            ],
            options={
                'verbose_name_plural': 'equity security master',
            },
        ),
        migrations.CreateModel(
            name='Portfolio_ExAnte_Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_return', models.FloatField(blank=True, null=True)),
                ('beta_to_b', models.FloatField(blank=True, null=True, verbose_name='beta to benchmark')),
                ('alpha_to_b', models.FloatField(blank=True, null=True, verbose_name='alpha to benchmark')),
                ('info_ratio', models.FloatField(blank=True, null=True, verbose_name='informational ratio')),
                ('commit_maker', models.CharField(blank=True, default='anonymous', max_length=40, null=True)),
                ('is_latest', models.BooleanField(default=True)),
                ('commit_time', models.CharField(default='2021-08-25@17:26:41', editable=False, max_length=40)),
            ],
            options={
                'verbose_name_plural': 'portfolio ex-ante stats',
            },
        ),
        migrations.CreateModel(
            name='Portfolio_Performance',
            fields=[
                ('date', models.DateField(default=django.utils.timezone.now, primary_key=True, serialize=False)),
                ('ex_ante_portfolio_risk_total', models.FloatField(blank=True, null=True, verbose_name='ex_ante_portfolio_risk_total')),
                ('ex_ante_portfolio_risk_active', models.FloatField(blank=True, null=True, verbose_name='ex_ante_portfolio_risk_active')),
                ('realized_portfolio_risk_active', models.FloatField(blank=True, null=True)),
                ('realized_portfolio_risk_total', models.FloatField(blank=True, null=True)),
                ('ex_ante_portfolio_benchmark_beta_total', models.FloatField(blank=True, null=True, verbose_name='ex_ante_portfolio_benchmark_beta_total')),
                ('ex_ante_portfolio_benchmark_beta_active', models.FloatField(blank=True, null=True, verbose_name='ex_ante_portfolio_benchmark_beta_active')),
                ('portfolio_diversity_coefficient_total', models.FloatField(blank=True, null=True, verbose_name='portfolio_diversity_coefficient_total')),
                ('portfolio_diversity_coefficient_active', models.FloatField(blank=True, null=True, verbose_name='portfolio_diversity_coefficient_active')),
                ('ex_ante_momentum_total', models.FloatField(blank=True, null=True, verbose_name='ex_ante_momentum_total')),
                ('ex_ante_momentum_active', models.FloatField(blank=True, null=True, verbose_name='ex_ante_momentum_active')),
                ('ex_ante_size_total', models.FloatField(blank=True, null=True, verbose_name='ex_ante_size_total')),
                ('ex_ante_size_active', models.FloatField(blank=True, null=True, verbose_name='ex_ante_size_active')),
                ('ex_ante_value_total', models.FloatField(blank=True, null=True, verbose_name='ex_ante_value_total')),
                ('ex_ante_value_active', models.FloatField(blank=True, null=True, verbose_name='ex_ante_value_active')),
                ('ex_ante_quality_total', models.FloatField(blank=True, null=True, verbose_name='ex_ante_quality_total')),
                ('ex_ante_quality_active', models.FloatField(blank=True, null=True, verbose_name='ex_ante_quality_active')),
                ('ex_ante_low_volatility_total', models.FloatField(blank=True, null=True, verbose_name='ex_ante_low_volatility_total')),
                ('ex_ante_low_volatility_active', models.FloatField(blank=True, null=True, verbose_name='ex_ante_low_volatility_active')),
                ('ex_ante_low_beta_total', models.FloatField(blank=True, null=True, verbose_name='ex_ante_low_beta_total')),
                ('ex_ante_low_beta_active', models.FloatField(blank=True, null=True, verbose_name='ex_ante_low_beta_active')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='positions', serialize=False, to='api.equity_security_master', verbose_name='asset id')),
                ('ticker', models.CharField(blank=True, max_length=40, null=True, verbose_name='ticker')),
                ('num_of_shares', models.IntegerField(blank=True, null=True, verbose_name='num of shares')),
                ('asset_type', models.CharField(blank=True, max_length=40, null=True, verbose_name='asset type')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='price')),
                ('position_value', models.FloatField(blank=True, null=True, verbose_name='position value')),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('trade_id', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='trade id')),
                ('trade_type', models.CharField(blank=True, max_length=40, null=True, verbose_name='trade type')),
                ('num_of_shares', models.IntegerField(blank=True, null=True, verbose_name='num of shares')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='price')),
                ('tot_price', models.FloatField(blank=True, null=True, verbose_name='tot price')),
                ('trade_status', models.CharField(blank=True, max_length=40, null=True, verbose_name='status')),
                ('trade_time', models.CharField(blank=True, max_length=40, null=True, verbose_name='date time')),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='trades', to='api.equity_security_master', verbose_name='asset id')),
            ],
        ),
        migrations.CreateModel(
            name='Security_Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('exante_total_annual_standard_deviation', models.FloatField(blank=True, null=True, verbose_name='annualized risk total')),
                ('exante_active_annual_standard_deviation', models.FloatField(blank=True, null=True, verbose_name='annualized risk active')),
                ('exante_total_annual_standard_deviation_partial', models.FloatField(blank=True, null=True, verbose_name='annualized risk total partial contribution')),
                ('exante_active_annual_standard_deviation_partial', models.FloatField(blank=True, null=True, verbose_name='annualized risk active partial contribution')),
                ('exante_total_annual_standard_deviation_contrib', models.FloatField(blank=True, null=True, verbose_name='annualized risk total contribution')),
                ('exante_active_annual_standard_deviation_contrib', models.FloatField(blank=True, null=True, verbose_name='annualized risk total contribution')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.equity_security_master', verbose_name='asset id')),
            ],
        ),
        migrations.CreateModel(
            name='Market_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caldt', models.DateTimeField(verbose_name='date')),
                ('shrcd', models.CharField(blank=True, max_length=40, null=True, verbose_name='share code')),
                ('siccd', models.CharField(blank=True, max_length=40, null=True, verbose_name='sic code')),
                ('prc', models.FloatField(blank=True, null=True, verbose_name='close price')),
                ('vol', models.IntegerField(blank=True, null=True, verbose_name='volume')),
                ('ret', models.FloatField(blank=True, null=True, verbose_name='return')),
                ('shr', models.FloatField(blank=True, null=True, verbose_name='shares outstanding')),
                ('rf', models.FloatField(blank=True, null=True, verbose_name='risk free rate')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='market_data', to='api.equity_security_master', verbose_name='asset id')),
            ],
        ),
        migrations.CreateModel(
            name='Live_Target_Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=40)),
                ('model_er', models.FloatField(verbose_name='model expected return')),
                ('annualized_er', models.FloatField(verbose_name='annualized expected return')),
                ('beta_to_b', models.FloatField(verbose_name='beta to benchmark')),
                ('alpha', models.FloatField()),
                ('oa_weight', models.FloatField(verbose_name='optimal active weight')),
                ('b_weight', models.FloatField(verbose_name='weight in benchmark')),
                ('c_weight', models.FloatField(verbose_name='current weight')),
                ('backlog', models.FloatField()),
                ('backlog_risk', models.FloatField()),
                ('commit_maker', models.CharField(blank=True, default='anonymous', max_length=40, null=True)),
                ('is_latest', models.BooleanField(default=False)),
                ('commit_time', models.CharField(default='2021-08-25@17:26:41', editable=False, max_length=40)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='live_target_portfolio', to='api.equity_security_master', verbose_name='asset id')),
            ],
            options={
                'verbose_name_plural': 'live target portfolio',
            },
        ),
    ]
